GETOB          Version 1.2.9  14 Aug 2001
Please cite: Fristensky B. (1993) Feature expressions:
creating and manipulating sequence datasets.
Nucl. Acids Res. 21:5997-6003

PEADRRA:CDS1
     66         545


/note="disease resistance response protein"
/codon_start=1
/translation="MGVFNVEDEITSVVAPAILYKALVTDADTLTPKVIDAIKSIEIV
EGNGGAGTIKKLTFVEDGETKHVLHKVELVDVANLAYNYSIVGGVGFPDTVEKISFEA
KLSAGPNGGSIAKLSVKYYTKGDAAAPTEEQLKSDKAKGDGLFKALERYCLAHPDYN"
//----------------------------------------------
PEADRRB:CDS1
    <1         528


/note="disease resistance response protein"
/codon_start=1
/translation="VFVMLFALSSAIPNKRKPYKPCKNLVFYFHDILYNGKNAANATS
AIVAAPEGVSLTKLAPQSHFGNIIVFDDPITLSHSLSSKQVGRAQGFYIYDTKNTYTS
WLSFTFVLNSTHHQGTITFAGADPIVAKTRDISVTGGTGDFFMHRGIATITTDAFEGE
AYFRLGVYIKFFECW"
//----------------------------------------------
PEADRRG:CDS1
    join           
        (
             1151                 1331

             1420                 1715

        )


/note="disease resistance response protein (DRRG49-c)"
/codon_start=1
/translation="MGVFNFEEEATSIVAPATLHKALVTDADILTPKVIDAIKSIEIV
EGNGGPGTIKKLTFVEDGETKYVLHKVELVDDANWANNYSIVGGVGLPDTVEKISFEA
KLSAGPNGGSIAKLSVKYYTKGDAIPSEEEIKNGKAKGEGIFKALEGYCVANPDYN"
//----------------------------------------------
